apiVersion: v1
kind: Pod
metadata:
  name: postgress-pod
  labels:
    name: postgress-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgress
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRESS_USER
          value: postgress
        - name: POSTGRESS_PASSWORD
          value: postgress
