apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pods
  labels:
    name: worker-app-pods
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
