apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  labels:
    app: flask-app
    type: fullstack
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30004
  selector:
    app: flask-app
    type: fullstack