apiVersion: v1
kind: Pod
metadata:
  name: application-backend
  labels:
    app: application-backend
spec:
  containers:
    - name: application-backend
      image: docker.io/tuheen27/application-backend:v0.2