apiVersion: v1
kind: Pod
metadata:
  name: 2-nd-application-frontend
  labels:
    app: 2-nd-application-frontend
    tier: frontend
spec:
  containers:
    - name: 2-nd-application-frontend
      image: docker.io/tuheen27/application-frontend:v.0