apiVersion: v1
kind: Pod
metadata:
  name: application-frontend
  labels:
    app: application-frontend
    tier: frontend
spec:
  containers:
    - name: application-frontend
      image: docker.io/tuheen27/application-frontend:latest
      ports:
        - containerPort: 5000
      env:
        - name: MONGO_URI
          value: "mongodb://mongodb-svc:27017/"